import type { EntranceRestriction, Game, LocationReference } from '../types';

// Primary area nodes
const dk64Nodes: LocationReference[] = [
  { id: 'training', name: 'Training Ground' },
  { id: 'isles', name: 'DK Isles' },
  { id: 'japes', name: 'Jungle Japes' },
  { id: 'aztec', name: 'Angry Aztec' },
  { id: 'factory', name: 'Frantic Factory' },
  { id: 'galleon', name: 'Gloomy Galleon' },
  { id: 'forest', name: 'Fungi Forest' },
  { id: 'caves', name: 'Crystal Caves' },
  { id: 'castle', name: 'Creepy Castle' },
];

// Exits array
const dk64Exits: LocationReference[] = [
  // Training Ground
  { id: 'training-treehouse', name: 'Training Ground → DK\'s Treehouse', uiGroup: 'Training Ground', parentNodeId: 'training', arrowType: '<-->', bidirectionalPair: 'treehouse-training' },
  { id: 'treehouse-training', name: 'DK\'s Treehouse → Training Ground', uiGroup: 'Training Ground', parentNodeId: 'training', arrowType: '<-->', bidirectionalPair: 'training-treehouse' },
  { id: 'training-isles', name: 'Training Ground → DK Isles', uiGroup: 'Training Ground', parentNodeId: 'training', arrowType: '<-->', bidirectionalPair: 'isles-training' },
  
  // DK Isles
  { id: 'isles-training', name: 'DK Isles → Training Ground', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'training-isles' },
  { id: 'isles-japes-lobby', name: 'DK Isles → Japes Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'japes-lobby-isles' },
  { id: 'isles-aztec-lobby', name: 'DK Isles → Aztec Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'aztec-lobby-isles' },
  { id: 'isles-factory-lobby', name: 'DK Isles → Factory Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'factory-lobby-isles' },
  { id: 'isles-galleon-lobby', name: 'DK Isles → Galleon Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'galleon-lobby-isles' },
  { id: 'isles-fungi-lobby', name: 'DK Isles → Fungi Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'fungi-lobby-isles' },
  { id: 'isles-caves-lobby', name: 'DK Isles → Caves Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'caves-lobby-isles' },
  { id: 'isles-castle-lobby', name: 'DK Isles → Castle Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'castle-lobby-isles' },
  { id: 'isles-helm-lobby', name: 'DK Isles → Helm Lobby', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'helm-lobby-isles' },
  { id: 'isles-lumsy', name: 'DK Isles → K. Lumsy\'s Room', tags: ['klumsy'], uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'lumsy-isles' },
  { id: 'lumsy-isles', name: 'K. Lumsy\'s Room → DK Isles', tags: ['klumsy'], uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-lumsy' },
  { id: 'isles-banana-fairy', name: 'DK Isles → Banana Fairy', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'banana-fairy-isles' },
  { id: 'banana-fairy-isles', name: 'Banana Fairy → DK Isles', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-banana-fairy' },
  { id: 'isles-snide', name: 'DK Isles → Snide Hideout', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'snide-isles' },
  { id: 'snide-isles', name: 'Snide Hideout → DK Isles', uiGroup: 'DK Isles', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-snide' },

  // Level Lobby
  { id: 'japes-lobby-entrance', name: 'Japes Lobby → Japes Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'japes-entrance-lobby' },
  { id: 'japes-lobby-isles', name: 'Japes Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-japes-lobby' },
  { id: 'aztec-lobby-entrance', name: 'Aztec Lobby → Aztec Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'aztec-entrance-lobby' },
  { id: 'aztec-lobby-isles', name: 'Aztec Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-aztec-lobby' },
  { id: 'factory-lobby-entrance', name: 'Factory Lobby → Factory Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'factory-entrance-lobby' },
  { id: 'factory-lobby-isles', name: 'Factory Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-factory-lobby' },
  { id: 'galleon-lobby-entrance', name: 'Galleon Lobby → Galleon Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'galleon-entrance-lobby' },
  { id: 'galleon-lobby-isles', name: 'Galleon Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-galleon-lobby' },
  { id: 'fungi-lobby-entrance', name: 'Fungi Lobby → Fungi Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'fungi-entrance-lobby' },
  { id: 'fungi-lobby-isles', name: 'Fungi Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-fungi-lobby' },
  { id: 'caves-lobby-entrance', name: 'Caves Lobby → Caves Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'caves-entrance-lobby' },
  { id: 'caves-lobby-isles', name: 'Caves Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-caves-lobby' },
  { id: 'castle-lobby-entrance', name: 'Castle Lobby → Castle Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'castle-entrance-lobby' },
  { id: 'castle-lobby-isles', name: 'Castle Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-castle-lobby' },
  { id: 'helm-lobby-entrance', name: 'Helm Lobby → Helm Level Entrance', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'helm-entrance-lobby' },
  { id: 'helm-entrance-lobby', name: 'Helm Level Entrance → Helm Lobby', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'helm-lobby-entrance' },
  { id: 'helm-lobby-isles', name: 'Helm Lobby → DK Isles', uiGroup: 'Level Lobby', parentNodeId: 'isles', arrowType: '<-->', bidirectionalPair: 'isles-helm-lobby' },

  // Jungle Japes
  { id: 'japes-entrance-lobby', name: 'Japes Level Entrance → Japes Lobby', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'japes-lobby-entrance' },
  { id: 'japes-main-diddy', name: 'Japes Main → Diddy Mountain', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'diddy-japes-main' },
  { id: 'diddy-japes-main', name: 'Diddy Mountain → Japes Main', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'japes-main-diddy' },
  { id: 'japes-main-lanky', name: 'Japes Main → Lanky Painting Room', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'lanky-japes-main' },
  { id: 'lanky-japes-main', name: 'Lanky Painting Room → Japes Main', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'japes-main-lanky' },
  { id: 'japes-main-chunky', name: 'Japes Main → Chunky Underground', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'chunky-japes-main' },
  { id: 'chunky-japes-main', name: 'Chunky Underground → Japes Main', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'japes-main-chunky' },
  { id: 'japes-main-tiny-beehive', name: 'Japes Main → Tiny Beehive', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'tiny-beehive-japes-main' },
  { id: 'tiny-beehive-japes-main', name: 'Tiny Beehive → Japes Main', uiGroup: 'Jungle Japes', parentNodeId: 'japes', arrowType: '<-->', bidirectionalPair: 'japes-main-tiny-beehive' },

  // Angry Aztec
  { id: 'aztec-entrance-lobby', name: 'Aztec Level Entrance → Aztec Lobby', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-lobby-entrance' },
  { id: 'aztec-main-tiny-temple', name: 'Aztec Main → Tiny Temple', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'tiny-temple-aztec-main' },
  { id: 'tiny-temple-aztec-main', name: 'Tiny Temple → Aztec Main', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-tiny-temple' },
  { id: 'aztec-main-llama-temple', name: 'Aztec Main → Llama Temple', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'llama-temple-aztec-main' },
  { id: 'llama-temple-aztec-main', name: 'Llama Temple → Aztec Main', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-llama-temple' },
  { id: 'aztec-main-dk-5d-temple', name: 'Aztec Main → DK 5D Temple', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'dk-5d-temple-aztec-main' },
  { id: 'dk-5d-temple-aztec-main', name: 'DK 5D Temple → Aztec Main', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-dk-5d-temple' },
  { id: 'aztec-main-diddy-5d-temple', name: 'Aztec Main → Diddy 5D Temple', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'diddy-5d-temple-aztec-main' },
  { id: 'diddy-5d-temple-aztec-main', name: 'Diddy 5D Temple → Aztec Main', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-diddy-5d-temple' },
  { id: 'aztec-main-lanky-5d-temple', name: 'Aztec Main → Lanky 5D Temple', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'lanky-5d-temple-aztec-main' },
  { id: 'lanky-5d-temple-aztec-main', name: 'Lanky 5D Temple → Aztec Main', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-lanky-5d-temple' },
  { id: 'aztec-main-tiny-5d-temple', name: 'Aztec Main → Tiny 5D Temple', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'tiny-5d-temple-aztec-main' },
  { id: 'tiny-5d-temple-aztec-main', name: 'Tiny 5D Temple → Aztec Main', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-tiny-5d-temple' },
  { id: 'aztec-main-chunky-5d-temple', name: 'Aztec Main → Chunky 5D Temple', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'chunky-5d-temple-aztec-main' },
  { id: 'chunky-5d-temple-aztec-main', name: 'Chunky 5D Temple → Aztec Main', tags: ['five door', 'five-door'], uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-chunky-5d-temple' },
  { id: 'aztec-main-tiny-beetle-race', name: 'Aztec Main → Tiny Beetle Race', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'tiny-beetle-race-aztec-main' },
  { id: 'tiny-beetle-race-aztec-main', name: 'Tiny Beetle Race → Aztec Main', uiGroup: 'Angry Aztec', parentNodeId: 'aztec', arrowType: '<-->', bidirectionalPair: 'aztec-main-tiny-beetle-race' },

  // Frantic Factory
  { id: 'factory-entrance-lobby', name: 'Factory Level Entrance → Factory Lobby', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'factory-lobby-entrance' },
  { id: 'factory-main-arcade', name: 'Factory Main → Arcade', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'arcade-factory-main' },
  { id: 'arcade-factory-main', name: 'Arcade → Factory Main', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'factory-main-arcade' },
  { id: 'factory-main-dk-crusher', name: 'Factory Main → DK Crucher Room', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'dk-crusher-factory-main' },
  { id: 'dk-crusher-factory-main', name: 'DK Crucher Room → Factory Main', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'factory-main-dk-crusher' },
  { id: 'factory-main-dk-power-shed', name: 'Factory Main → DK Power Shed', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'dk-power-shed-factory-main' },
  { id: 'dk-power-shed-factory-main', name: 'DK Power Shed → Factory Main', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'factory-main-dk-power-shed' },
  { id: 'factory-main-tiny-car-race', name: 'Factory Main → Tiny Car Race', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'tiny-car-race-factory-main' },
  { id: 'tiny-car-race-factory-main', name: 'Tiny Car Race → Factory Main', uiGroup: 'Frantic Factory', parentNodeId: 'factory', arrowType: '<-->', bidirectionalPair: 'factory-main-tiny-car-race' },

  // Gloomy Galleon
  { id: 'galleon-entrance-lobby', name: 'Galleon Level Entrance → Galleon Lobby', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-lobby-entrance' },
  { id: 'galleon-main-dk-lighthouse', name: 'Galleon Main → DK Lighthouse', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'dk-lighthouse-galleon-main' },
  { id: 'dk-lighthouse-galleon-main', name: 'DK Lighthouse → Galleon Main', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-dk-lighthouse' },
  { id: 'galleon-main-chunky-seasick', name: 'Galleon Main → Chunky Seasick Ship', tags: ['drunky', 'sick bay'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'chunky-seasick-galleon-main' },
  { id: 'chunky-seasick-galleon-main', name: 'Chunky Seasick Ship → Galleon Main', tags: ['drunky', 'sick bay'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-chunky-seasick' },
  { id: 'galleon-main-tiny-mermaid', name: 'Galleon Main → Tiny Mermaid', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'tiny-mermaid-galleon-main' },
  { id: 'tiny-mermaid-galleon-main', name: 'Tiny Mermaid → Galleon Main', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-tiny-mermaid' },
  { id: 'galleon-main-tiny-treasure', name: 'Galleon Main → Tiny Treasure Chest', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'tiny-treasure-galleon-main' },
  { id: 'tiny-treasure-galleon-main', name: 'Tiny Treasure Chest → Galleon Main', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-tiny-treasure' },
  { id: 'galleon-main-dk-5d-ship', name: 'Galleon Main → DK 5D Ship (#3)', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'dk-5d-ship-galleon-main' },
  { id: 'dk-5d-ship-galleon-main', name: 'DK 5D Ship (#3) → Galleon Main', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-dk-5d-ship' },
  { id: 'galleon-main-diddy-5d-ship', name: 'Galleon Main → Diddy 5D Ship (#2)', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'diddy-5d-ship-galleon-main' },
  { id: 'diddy-5d-ship-galleon-main', name: 'Diddy 5D Ship (#2) → Galleon Main', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-diddy-5d-ship' },
  { id: 'galleon-main-lanky-5d-ship', name: 'Galleon Main → Lanky 5D Ship (#4)', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'lanky-5d-ship-galleon-main' },
  { id: 'lanky-5d-ship-galleon-main', name: 'Lanky 5D Ship (#4) → Galleon Main', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-lanky-5d-ship' },
  { id: 'galleon-main-tiny-5d-ship', name: 'Galleon Main → Tiny 5D Ship (#5)', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'tiny-5d-ship-galleon-main' },
  { id: 'tiny-5d-ship-galleon-main', name: 'Tiny 5D Ship (#5) → Galleon Main', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-tiny-5d-ship' },
  { id: 'galleon-main-chunky-5d-ship', name: 'Galleon Main → Chunky 5D Ship (Top)', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'chunky-5d-ship-galleon-main' },
  { id: 'chunky-5d-ship-galleon-main', name: 'Chunky 5D Ship (Top) → Galleon Main', tags: ['five door', 'five-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-chunky-5d-ship' },
  { id: 'galleon-main-lanky-2d-ship', name: 'Galleon Main → Lanky 2D Ship', tags: ['two door', 'two-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'lanky-2d-ship-galleon-main' },
  { id: 'lanky-2d-ship-galleon-main', name: 'Lanky 2D Ship → Galleon Main', tags: ['two door', 'two-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-lanky-2d-ship' },
  { id: 'galleon-main-tiny-2d-ship', name: 'Galleon Main → Tiny 2D Ship', tags: ['two door', 'two-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'tiny-2d-ship-galleon-main' },
  { id: 'tiny-2d-ship-galleon-main', name: 'Tiny 2D Ship → Galleon Main', tags: ['two door', 'two-door'], uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-tiny-2d-ship' },
  { id: 'galleon-main-tiny-submarine', name: 'Galleon Main → Tiny Submarine', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'tiny-submarine-galleon-main' },
  { id: 'tiny-submarine-galleon-main', name: 'Tiny Submarine → Galleon Main', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-tiny-submarine' },
  { id: 'galleon-main-mech-fish', name: 'Galleon Main → Mech Fish', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'mech-fish-galleon-main' },
  { id: 'mech-fish-galleon-main', name: 'Mech Fish → Galleon Main', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-mech-fish' },
  { id: 'galleon-main-dk-seal-race', name: 'Galleon Main → DK Seal Race', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'dk-seal-race-galleon-main' },
  { id: 'dk-seal-race-galleon-main', name: 'DK Seal Race → Galleon Main', uiGroup: 'Gloomy Galleon', parentNodeId: 'galleon', arrowType: '<-->', bidirectionalPair: 'galleon-main-dk-seal-race' },

  // Fungi Forest
  { id: 'fungi-entrance-lobby', name: 'Fungi Level Entrance → Fungi Lobby', uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-lobby-entrance' },
  { id: 'fungi-main-mill-front', name: 'Fungi Main → Mill Front Door', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'mill-front-fungi-main' },
  { id: 'mill-front-fungi-main', name: 'Mill Front Door → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-mill-front' },
  { id: 'front-mill-tiny-back-mill-tiny', name: 'Front Mill Tiny Hole → Back Mill Tiny Hole', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'back-mill-tiny-front-mill-tiny' },
  { id: 'back-mill-tiny-front-mill-tiny', name: 'Back Mill Tiny Hole → Front Mill Tiny Hole', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'front-mill-tiny-back-mill-tiny' },
  { id: 'fungi-main-mill-back', name: 'Fungi Main → Mill Back Door', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'mill-back-fungi-main' },
  { id: 'mill-back-fungi-main', name: 'Mill Back Door → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-mill-back' },
  { id: 'back-mill-spider-room', name: 'Back Mill → Spider Room', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'spider-room-back-mill' },
  { id: 'spider-room-back-mill', name: 'Spider Room → Back Mill', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'back-mill-spider-room' },
  { id: 'fungi-main-back-mill-tiny', name: 'Fungi Main → Back Mill Tiny Hole', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'back-mill-tiny-fungi-main' },
  { id: 'back-mill-tiny-fungi-main', name: 'Back Mill Tiny Hole → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-back-mill-tiny' },
  { id: 'fungi-main-lanky-mill-attic', name: 'Fungi Main → Lanky Mill Attic', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'lanky-mill-attic-fungi-main' },
  { id: 'lanky-mill-attic-fungi-main', name: 'Lanky Mill Attic → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-lanky-mill-attic' },
  { id: 'fungi-main-diddy-winch', name: 'Fungi Main → Diddy Winch Room', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'diddy-winch-fungi-main' },
  { id: 'diddy-winch-fungi-main', name: 'Diddy Winch Room → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-diddy-winch' },
  { id: 'fungi-main-diddy-dark-rafters', name: 'Fungi Main → Diddy Dark Rafters', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'diddy-dark-rafters-fungi-main' },
  { id: 'diddy-dark-rafters-fungi-main', name: 'Diddy Dark Rafters → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-diddy-dark-rafters' },
  { id: 'fungi-main-dk-thornvine', name: 'Fungi Main → DK Thornvine Barn', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'dk-thornvine-fungi-main' },
  { id: 'dk-thornvine-fungi-main', name: 'DK Thornvine Barn → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-dk-thornvine' },
  { id: 'fungi-main-giant-mushroom-base', name: 'Fungi Main → Giant Mushroom Base', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'giant-mushroom-base-fungi-main' },
  { id: 'giant-mushroom-base-fungi-main', name: 'Giant Mushroom Base → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-giant-mushroom-base' },
  { id: 'fungi-main-giant-mushroom-middle-low', name: 'Fungi Main → Giant Mushroom Middle Low', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'giant-mushroom-middle-low-fungi-main' },
  { id: 'giant-mushroom-middle-low-fungi-main', name: 'Giant Mushroom Middle Low → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-giant-mushroom-middle-low' },
  { id: 'fungi-main-giant-mushroom-middle-high', name: 'Fungi Main → Giant Mushroom Middle High', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'giant-mushroom-middle-high-fungi-main' },
  { id: 'giant-mushroom-middle-high-fungi-main', name: 'Giant Mushroom Middle High → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-giant-mushroom-middle-high' },
  { id: 'fungi-main-giant-mushroom-night', name: 'Fungi Main → Giant Mushroom Night Door', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'giant-mushroom-night-fungi-main' },
  { id: 'giant-mushroom-night-fungi-main', name: 'Giant Mushroom Night Door → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-giant-mushroom-night' },
  { id: 'fungi-main-giant-mushroom-top', name: 'Fungi Main → Giant Mushroom Top', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'giant-mushroom-top-fungi-main' },
  { id: 'giant-mushroom-top-fungi-main', name: 'Giant Mushroom Top → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-giant-mushroom-top' },
  { id: 'fungi-main-chunky-face', name: 'Fungi Main → Chunky Face Puzzle', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'chunky-face-fungi-main' },
  { id: 'chunky-face-fungi-main', name: 'Chunky Face Puzzle → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-chunky-face' },
  { id: 'fungi-main-lanky-bouncy-mushroom', name: 'Fungi Main → Lanky Bouncy Mushroom', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'lanky-bouncy-mushroom-fungi-main' },
  { id: 'lanky-bouncy-mushroom-fungi-main', name: 'Lanky Bouncy Mushroom → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-lanky-bouncy-mushroom' },
  { id: 'fungi-main-lanky-mushroom-puzzle', name: 'Fungi Main → Lanky Mushroom Puzzle', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'lanky-mushroom-puzzle-fungi-main' },
  { id: 'lanky-mushroom-puzzle-fungi-main', name: 'Lanky Mushroom Puzzle → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-lanky-mushroom-puzzle' },
  { id: 'fungi-main-tiny-anthill', name: 'Fungi Main → Tiny Anthill', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'tiny-anthill-fungi-main' },
  { id: 'tiny-anthill-fungi-main', name: 'Tiny Anthill → Fungi Main', tags: ['fungi', 'forest'], uiGroup: 'Fungi Forest', parentNodeId: 'forest', arrowType: '<-->', bidirectionalPair: 'fungi-main-tiny-anthill' },

  // Crystal Caves
  { id: 'caves-entrance-lobby', name: 'Caves Level Entrance → Caves Lobby', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-lobby-entrance' },
  { id: 'caves-lanky-ice-castle', name: 'Crystal Caves → Lanky Ice Castle', tags: ['slam challenge'], uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'lanky-ice-castle-caves' },
  { id: 'lanky-ice-castle-caves', name: 'Lanky Ice Castle → Crystal Caves', tags: ['slam challenge'], uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-lanky-ice-castle' },
  { id: 'caves-lanky-beetle-race', name: 'Crystal Caves → Lanky Beetle Race', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'lanky-beetle-race-caves' },
  { id: 'lanky-beetle-race-caves', name: 'Lanky Beetle Race → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-lanky-beetle-race' },
  { id: 'caves-dk-5d-cabin', name: 'Crystal Caves → DK 5D Cabin', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'dk-5d-cabin-caves' },
  { id: 'dk-5d-cabin-caves', name: 'DK 5D Cabin → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-dk-5d-cabin' },
  { id: 'caves-diddy-lower-5d-cabin', name: 'Crystal Caves → Diddy Lower 5D Cabin', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'diddy-lower-5d-cabin-caves' },
  { id: 'diddy-lower-5d-cabin-caves', name: 'Diddy Lower 5D Cabin → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-diddy-lower-5d-cabin' },
  { id: 'caves-diddy-upper-5d-cabin', name: 'Crystal Caves → Diddy Upper 5D Cabin', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'diddy-upper-5d-cabin-caves' },
  { id: 'diddy-upper-5d-cabin-caves', name: 'Diddy Upper 5D Cabin → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-diddy-upper-5d-cabin' },
  { id: 'caves-tiny-5d-cabin', name: 'Crystal Caves → Tiny 5D Cabin', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'tiny-5d-cabin-caves' },
  { id: 'tiny-5d-cabin-caves', name: 'Tiny 5D Cabin → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-tiny-5d-cabin' },
  { id: 'caves-chunky-5d-cabin', name: 'Crystal Caves → Chunky 5D Cabin', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'chunky-5d-cabin-caves' },
  { id: 'chunky-5d-cabin-caves', name: 'Chunky 5D Cabin → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-chunky-5d-cabin' },
  { id: 'caves-lanky-1d-cabin', name: 'Crystal Caves → Lanky 1D Cabin', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'lanky-1d-cabin-caves' },
  { id: 'lanky-1d-cabin-caves', name: 'Lanky 1D Cabin → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-lanky-1d-cabin' },
  { id: 'caves-dk-rotating-room', name: 'Crystal Caves → DK Rotating Room', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'dk-rotating-room-caves' },
  { id: 'dk-rotating-room-caves', name: 'DK Rotating Room → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-dk-rotating-room' },
  { id: 'caves-dk-5d-igloo', name: 'Crystal Caves → DK 5D Igloo', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'dk-5d-igloo-caves' },
  { id: 'dk-5d-igloo-caves', name: 'DK 5D Igloo → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-dk-5d-igloo' },
  { id: 'caves-diddy-5d-igloo', name: 'Crystal Caves → Diddy 5D Igloo', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'diddy-5d-igloo-caves' },
  { id: 'diddy-5d-igloo-caves', name: 'Diddy 5D Igloo → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-diddy-5d-igloo' },
  { id: 'caves-lanky-5d-igloo', name: 'Crystal Caves → Lanky 5D Igloo', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'lanky-5d-igloo-caves' },
  { id: 'lanky-5d-igloo-caves', name: 'Lanky 5D Igloo → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-lanky-5d-igloo' },
  { id: 'caves-tiny-5d-igloo', name: 'Crystal Caves → Tiny 5D Igloo', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'tiny-5d-igloo-caves' },
  { id: 'tiny-5d-igloo-caves', name: 'Tiny 5D Igloo → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-tiny-5d-igloo' },
  { id: 'caves-chunky-5d-igloo', name: 'Crystal Caves → Chunky 5D Igloo', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'chunky-5d-igloo-caves' },
  { id: 'chunky-5d-igloo-caves', name: 'Chunky 5D Igloo → Crystal Caves', uiGroup: 'Crystal Caves', parentNodeId: 'caves', arrowType: '<-->', bidirectionalPair: 'caves-chunky-5d-igloo' },

  // Creepy Castle
  { id: 'castle-entrance-lobby', name: 'Castle Level Entrance → Castle Lobby', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-lobby-entrance' },
  { id: 'castle-main-dk-chunky-tree', name: 'Castle Main → DK/Chunky Tree', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'dk-chunky-tree-castle-main' },
  { id: 'dk-chunky-tree-castle-main', name: 'DK/Chunky Tree → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-dk-chunky-tree' },
  { id: 'castle-main-lower-cave', name: 'Castle Main → Lower Cave', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'lower-cave-castle-main' },
  { id: 'lower-cave-castle-main', name: 'Lower Cave → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-lower-cave' },
  { id: 'lower-cave-mausoleum', name: 'Lower Cave → Mausoleum', uiGroup: 'Creepy Castle', tags: ['castle'], parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'mausoleum-lower-cave' },
  { id: 'mausoleum-lower-cave', name: 'Mausoleum → Lower Cave', uiGroup: 'Creepy Castle', tags: ['castle'], parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'lower-cave-mausoleum' },
  { id: 'lower-cave-crypt', name: 'Lower Cave → Crypt', uiGroup: 'Creepy Castle', tags: ['castle'], parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'crypt-lower-cave' },
  { id: 'crypt-lower-cave', name: 'Crypt → Lower Cave', uiGroup: 'Creepy Castle', tags: ['castle'], parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'lower-cave-crypt' },
  { id: 'crypt-dk-minecart', name: 'Crypt → DK Minecart', uiGroup: 'Creepy Castle', tags: ['castle'], parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'dk-minecart-crypt' },
  { id: 'dk-minecart-crypt', name: 'DK Minecart → Crypt', uiGroup: 'Creepy Castle', tags: ['castle'], parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'crypt-dk-minecart' },
  { id: 'castle-main-upper-cave-moat', name: 'Castle Main → Upper Cave (Moat Door)', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'upper-cave-moat-castle-main' },
  { id: 'upper-cave-moat-castle-main', name: 'Upper Cave (Moat Door) → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-upper-cave-moat' },
  { id: 'upper-cave-dungeon', name: 'Upper Cave → Dungeon', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'dungeon-upper-cave' },
  { id: 'dungeon-upper-cave', name: 'Dungeon → Upper Cave', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'upper-cave-dungeon' },
  { id: 'castle-main-upper-cave-back', name: 'Castle Main → Upper Cave (Back Door)', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'upper-cave-back-castle-main' },
  { id: 'upper-cave-back-castle-main', name: 'Upper Cave (Back Door) → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-upper-cave-back' },
  { id: 'castle-main-chunky-museum', name: 'Castle Main → Chunky Museum', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'chunky-museum-castle-main' },
  { id: 'chunky-museum-castle-main', name: 'Chunky Museum → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-chunky-museum' },
  { id: 'castle-main-tiny-trash-can', name: 'Castle Main → Tiny Trash Can', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'tiny-trash-can-castle-main' },
  { id: 'tiny-trash-can-castle-main', name: 'Tiny Trash Can → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-tiny-trash-can' },
  { id: 'castle-main-lanky-greenhouse', name: 'Castle Main → Lanky Greenhouse', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'lanky-greenhouse-entrance-castle-main' },
  { id: 'lanky-greenhouse-entrance-castle-main', name: 'Lanky Greenhouse Entrance → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-lanky-greenhouse' },
  { id: 'castle-main-chunky-shed', name: 'Castle Main → Chunky Shed', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'chunky-shed-castle-main' },
  { id: 'chunky-shed-castle-main', name: 'Chunky Shed → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-chunky-shed' },
  { id: 'castle-main-diddy-ballroom', name: 'Castle Main → Diddy Ballroom', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'diddy-ballroom-castle-main' },
  { id: 'diddy-ballroom-castle-main', name: 'Diddy Ballroom → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-diddy-ballroom' },
  { id: 'tiny-ballroom-tiny-museum', name: 'Tiny Ballroom → Tiny Museum', tags: ['castle'], uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'tiny-museum-tiny-ballroom' },
  { id: 'tiny-museum-tiny-ballroom', name: 'Tiny Museum → Tiny Ballroom', tags: ['castle'], uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'tiny-ballroom-tiny-museum' },
  { id: 'tiny-museum-tiny-car-race', name: 'Tiny Museum → Tiny Car Race', tags: ['castle'], uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'tiny-car-race-tiny-museum' },
  { id: 'tiny-car-race-tiny-museum', name: 'Tiny Car Race → Tiny Museum', tags: ['castle'], uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'tiny-museum-tiny-car-race' },
  { id: 'castle-main-dk-library', name: 'Castle Main → DK Library', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'dk-library-castle-main' },
  { id: 'dk-library-castle-main', name: 'DK Library → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-dk-library' },
  { id: 'castle-main-lanky-tower', name: 'Castle Main → Lanky Tower', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'lanky-tower-castle-main' },
  { id: 'lanky-tower-castle-main', name: 'Lanky Tower → Castle Main', uiGroup: 'Creepy Castle', parentNodeId: 'castle', arrowType: '<-->', bidirectionalPair: 'castle-main-lanky-tower' },
];

// Entrances array - all exits can be entrance destinations
const dk64Entrances: LocationReference[] = dk64Exits;

// Generate restrictions: every exit can connect to every other exit except itself
const dk64Restrictions: EntranceRestriction[] = dk64Exits.map(exit => ({
  gameId: 'dk64',
  exitId: exit.id,
  allowedEntranceIds: dk64Exits.filter(e => e.id !== exit.id).map(e => e.id),
}));

export const dk64: Game = {
  id: 'dk64',
  name: 'Donkey Kong 64',
  description: 'Loading zone randomizer',
  nodes: dk64Nodes,
  exits: dk64Exits,
  entrances: dk64Entrances,
  staticConnections: `
  graph TD;
  training["Training Ground"];
  isles["DK Isles"];
  japes["Jungle Japes"];
  aztec["Angry Aztec"];
  factory["Frantic Factory"];
  galleon["Gloomy Galleon"];
  forest["Fungi Forest"];
  caves["Crystal Caves"];
  castle["Creepy Castle"];
  `,
  restrictions: dk64Restrictions,
  options: [
    {
      id: 'decouple-transitions',
      name: 'Decouple Transitions',
      description: 'Have the transitions work in different directions?',
      defaultValue: 'false',
      values: [
        { id: 'false', description: 'No (Two-Way)' },
        { id: 'true', description: 'Yes (One-Way)' },
      ]
    },
  ],
  showMap: false,
  startUnselected: true,
  allowSwapOnDuplicate: false,
  hideDisabledOptions: true,
};
